dist: trusty

language: java
install:
  - npm install typescript
jdk:
  - oraclejdk8
before_script:
  - cd server
addons:
  sonarcloud:
    organization: "kuul-development"
script:
  -  mvn clean verify sonar:sonar -Pcoverage
  - cd ..
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'
