dist: trusty

language: java
jdk:
  - oraclejdk8
before_script:
  - cd server
addons:
  sonarcloud:
    organization: "kuul-development"
script:
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'
