
matrix:
  include:
    - language: java
      dist: trusty
      jdk: oraclejdk8
      addons:
        sonarcloud:
          organization: "kuul-development"
      before_script:
        - cd server
      script:
        - mvn clean install -Pcoverage
        - cd ..
        - sonar-scanner

    - language: node_js
      dist: xenial
      before_script:
        - cd ui
        - nvm install 13
        - nvm use node
        - npm install
      script:
        - ng build --prod
      deploy:
        provider: s3
        access_key_id: ${AWS_ACCESS_KEY_ID}
        secret_access_key: ${AWS_SECRET_ACCESS_KEY}
        bucket: "testbucket-pekr"
        skip_cleanup: true
        local_dir: dist/ui
        on:
          branch: cloud-deployment


#dist: trusty
#
#git:
#  depth: 3
#
#language: java
#install:
#  - npm install typescript
#jdk:
#  - oraclejdk8
#addons:
#  sonarcloud:
#    organization: "kuul-development"
#script:
#  - cd server
#  - mvn clean install -Pcoverage
#  - cd ../ui/
#  - npm install
#  - npm run-script build
#  - cd ..
#  - sonar-scanner
#cache:
#  directories:
#    - '$HOME/.sonar/cache'
#deploy:
#  provider: s3
#  access_key_id: "YOUR AWS ACCESS KEY"
#  secret_access_key: "YOUR AWS SECRET KEY"
#  bucket: "testbucket-pekr"
#  skip_cleanup: true
#  local_dir: build
#  on:
#    branch: cloud-deployment
