dist: trusty

git:
  depth: 3

language: java
install:
  - npm install typescript
  - cd ui
  - npm install
  - cd ..
jdk:
  - oraclejdk8
addons:
  sonarcloud:
    organization: "kuul-development"
script:
  - cd server
  - mvn clean install -Pcoverage
  - cd ../ui/
  - ng build --prod
  - cd ..
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'
deploy:
  provider: s3
  access_key_id: "YOUR AWS ACCESS KEY"
  secret_access_key: "YOUR AWS SECRET KEY"
  bucket: "testbucket-pekr"
  skip_cleanup: true
  local_dir: build
  on:
    branch: cloud-deployment
