
matrix:
  include:
    - language: java
      dist: trusty
      jdk: oraclejdk8
      before_script:
        - cd server
      script:
        - mvn clean install -Pcoverage

    - language: node_js
      dist: xenial
      node_js: '11.0.0'
      before_script:
        - cd ui
        - npm install -g angular/cli
        - npm install
      script:
        - ng build --prod


#dist: trusty
#
#git:
#  depth: 3
#
#language: java
#install:
#  - npm install typescript
#jdk:
#  - oraclejdk8
#addons:
#  sonarcloud:
#    organization: "kuul-development"
#script:
#  - cd server
#  - mvn clean install -Pcoverage
#  - cd ../ui/
#  - npm install
#  - npm run-script build
#  - cd ..
#  - sonar-scanner
#cache:
#  directories:
#    - '$HOME/.sonar/cache'
#deploy:
#  provider: s3
#  access_key_id: "YOUR AWS ACCESS KEY"
#  secret_access_key: "YOUR AWS SECRET KEY"
#  bucket: "testbucket-pekr"
#  skip_cleanup: true
#  local_dir: build
#  on:
#    branch: cloud-deployment
