dist: trusty

matrix:
  include:
    - language: java
      jdk:
        - oraclejdk8
      before_script:
        - cd server
      addons:
        sonarcloud:
          organization: "kuul-development"
      script:
          - sonar-scanner
